const database = require("./database.js");
const commentsDao = {
// task 1 create a article
    async createComment(articleId, parentId, userId, content) {
        const db = await database;

        const result = await db.query(
            'INSERT INTO lab_15_comments (articleId, parentId, UserId, content) VALUES (?, ?, ?, ?)',
            [articleId, parentId, userId, content]
        );

// get the id which generated by database
        const commentId = result.insertId;

        return commentId;
    },

    async getAllComments(articleId) {
            const db = await database;

            const comments = await db.query(
                'select * from lab_15_comments where ArticleId = ?', [articleId]
            );

            return comments;
        },

// 根据评论 ID 删除一条评论
    async deleteComment(commentId) {
        const db = await database;

        const result = await db.query('DELETE FROM lab_15_comments WHERE id = ?', [commentId]);

        return result.affectedRows > 0; // 如果删除了一行，则返回 true
    },

};



module.exports = commentsDao;